version: "3.9"

services:
  calculator-react:
    build: .
    ports:
      - "3000"
    networks:
      frontend:
    deploy:
      replicas: 1

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      frontend:


  nginx:
    image: nginx:latest
    ports:
      - "3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      frontend:
        ipv4_address: 172.21.0.23
    depends_on:
      - calculator-react

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.21.0.0/24
