version: "3.9"

services:
  react-calculator:
    build: .
    ports:
      - "80"
    networks:
      frontend:
        ipv4_address: 172.3.0.23
    deploy:
      replicas: 1

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      frontend:

networks:
  frontend:
    ipam:
      config:
        - subnet: 172.3.0.0/24
